local S=require('tests.support')
local G,A=S.G,S.A

local b=G.builder()
local R=b:membrane(nil,'place','R')
local P=b:membrane(R,'place','P')
local C=b:membrane(P,'place','C')
local Wrong=b:membrane(R,'place','Wrong')
local id=b:point(R,'X')
local rp=b:strand(P,'RP',{id})
local rc=b:strand(C,'RC',{id})
local rw=b:strand(Wrong,'RC',{id})
local base=b:finish()

-- A parent/child membrane pattern cannot bind its child to an unrelated sibling.
local p=G.builder()
local XR=p:membrane(nil,'place','R-pattern')
local X=p:membrane(XR,'place','X')
local Y=p:membrane(X,'place','Y')
local px=p:point(XR,'X')
local a=p:strand(X,'RP',{px})
local c=p:strand(Y,'RC',{px})
local pat=p:finish()
local ws=A.all(base,{P,C,Wrong},pat)
S.eq(#ws,1)
S.eq(ws[1]:membrane(X),P)
S.eq(ws[1]:membrane(Y),C)

-- Binding a child forces the pattern ancestor through membrane geometry.
local q=G.builder()
local QR=q:membrane(nil,'place','root-shell')
local QP=q:membrane(QR,'place','parent-shell')
local QC=q:membrane(QP,'place','child')
local qi=q:point(QR,'X')
q:strand(QC,'RC',{qi})
local child_only=q:finish()
local w=A.one(base,{C},child_only)
S.ok(w)
S.eq(w:membrane(QC),C)
S.eq(w:membrane(QP),P)
S.eq(w:membrane(QR),R)

-- A bound membrane may contain a fresh child. The fresh child is copied;
-- it is not flattened into the parent.
local f=G.builder()
local DR=f:membrane(nil,'place','root-pattern')
local D=f:membrane(DR,'place','D')
local Fresh=f:membrane(D,'place','Fresh')
local fp=f:point(DR,'X')
local din=f:strand(D,'RP',{fp})
local outp=f:point(Fresh,'FreshIdentity')
local out=f:strand(Fresh,'ChildR',{outp})
f:face(D,'spawn',{din},{out})
local spawn=f:finish()
local sw=A.one(base,{P},spawn); S.ok(sw)
local g2,img=A.glue(sw)
local fm=img.membranes[Fresh]
S.ok(fm and fm~=P)
S.eq(g2:parent(fm),P)
S.eq(g2:cell(img.strands[out]).membrane,fm)

print('ok 05_nested_membranes')
