local W=require('worlds'); local T=require('support')
local vb=W.Geometry.builder(); local vm=vb:membrane(nil,'v'); local R=vb:point(vm,'R'); vb:finish()
local a=W.Geometry.builder(); local am=a:membrane(nil,'a'); local ai=a:strand(am,{R}); local ao=a:strand(am,{R}); a:face(am,{ai},{ao}); local A=a:finish()
local b=W.Geometry.builder(); local bm=b:membrane(nil,'b'); local bi=b:strand(bm,{R}); local bo=b:strand(bm,{R}); b:face(bm,{bi},{bo}); local B=b:finish()
local c=W.Geometry.builder(); local cm=c:membrane(nil,'c'); local ci=c:strand(cm,{R}); local co=c:strand(cm,{R}); c:face(cm,{ci},{co}); local C=c:finish()
local ok1=pcall(function() W.Algebra.close({A,B,C},{{ao,bi},{ao,ci}}) end); T.ok(not ok1,'one scarce terminal output cannot close two inputs')
local ok2=pcall(function() W.Algebra.close({A,B,C},{{ao,bi},{co,bi}}) end); T.ok(not ok2,'one open input cannot be closed twice')
local ok3=pcall(function() W.Algebra.close({A,B},{{ai,bi}}) end); T.ok(not ok3,'cut source must be terminal')
local ok4=pcall(function() W.Algebra.close({A,B},{{ao,bo}}) end); T.ok(not ok4,'cut target must be open input')
local z=W.Geometry.builder(); local zm=z:membrane(nil,'z'); local zs=z:strand(zm,{R}); local Z=z:finish()
local ok5=pcall(function() W.Algebra.close({Z},{{zs,zs}}) end); T.ok(not ok5,'Cut must wire distinct scarce boundary occurrences; self-Cut is not closure')
return T.count()
