#!/usr/bin/env python3
"""Product-torus generators for the executable cube fibre.

21_cube_executable_formula.lua gives an exact combinatorial description of the
Worlds-developable vertices (tested exhaustively through q=6).  This script asks
whether their homology is opaque, or whether it is generated by products of
local one-coordinate triangles.

For q=4,5,6 every nonzero class found through H3 has such a product-torus
representative.
"""
from itertools import combinations,product
from math import comb

MASKS={0,1<<4,1<<5,(1<<4)|(1<<5),(1<<3)|(1<<4),(1<<3)|(1<<4)|(1<<5),
       (1<<2)|(1<<3)|(1<<4),(1<<2)|(1<<3)|(1<<4)|(1<<5),
       (1<<1)|(1<<2)|(1<<3)|(1<<4),(1<<1)|(1<<2)|(1<<3)|(1<<4)|(1<<5)}

def vertex_set(q):
    V=set()
    for d in product(range(q),repeat=6):
        mask=0; seen=set(); good=True
        for i,s in enumerate(d):
            if s:
                mask|=1<<i
                if s>=2:
                    if s in seen: good=False; break
                    seen.add(s)
        if good and mask in MASKS:
            V.add(sum(s*q**i for i,s in enumerate(d)))
    return V

def analyse(q,maxr):
    V=vertex_set(q); pw=[q**i for i in range(6)]
    def dec(c):
        d=[]
        for _ in range(6): d.append(c%q); c//=q
        return tuple(d)
    def enc(d): return sum(v*pw[i] for i,v in enumerate(d))
    cache={}
    def cells(k):
        if k in cache:return cache[k]
        if k==0: out=[dec(c) for c in sorted(V)]
        else:
            out=[]
            for code in sorted(V):
                base=dec(code)
                for act in combinations(range(6),k):
                    opts=[range(base[i]+1,q) for i in act]
                    if any(len(x)==0 for x in opts):continue
                    for ups in product(*opts):
                        spec=list(base)
                        for i,u in zip(act,ups):spec[i]=(base[i],u)
                        good=True
                        for bits in product((0,1),repeat=k):
                            d=list(base)
                            for i,u,b in zip(act,ups,bits):d[i]=u if b else base[i]
                            if enc(d) not in V:good=False;break
                        if good:out.append(tuple(spec))
        cache[k]=out;return out
    def boundary(c):
        for i,x in enumerate(c):
            if isinstance(x,tuple):
                for v in x:
                    y=list(c);y[i]=v;yield tuple(y)
    def add(x,b):
        while x:
            p=x.bit_length()-1
            if p in b:x^=b[p]
            else:b[p]=x;return True
        return False
    def image_basis(r,idx):
        basis={}
        if r>=6:return basis
        for c in cells(r+1):
            x=0
            for f in boundary(c):x^=1<<idx[f]
            add(x,basis)
        return basis
    # Betti by ranks, so candidate span can be checked against an independent target.
    C=[cells(k) for k in range(maxr+2)]
    ranks=[0]*(maxr+2)
    for r in range(1,maxr+2):
        idx={c:i for i,c in enumerate(C[r-1])}; b={}
        for c in C[r]:
            x=0
            for f in boundary(c):x^=1<<idx[f]
            add(x,b)
        ranks[r]=len(b)
    betti=[len(C[r])-ranks[r]-(ranks[r+1] if r+1<len(ranks) else 0) for r in range(maxr+1)]

    results={}
    triangles=list(combinations(range(q),3)); tri_edges={t:list(combinations(t,2)) for t in triangles}
    for r in range(1,maxr+1):
        Cr=cells(r); idx={c:i for i,c in enumerate(Cr)}; basis=image_basis(r,idx); found=0; byact={}
        for act in combinations(range(6),r):
            fixed=[i for i in range(6) if i not in act]
            for vals in product(range(q),repeat=len(fixed)):
                base=[None]*6
                for i,v in zip(fixed,vals):base[i]=v
                if r==1:
                    tri_sets=((t,) for t in triangles)
                elif r==2:
                    tri_sets=product(triangles,repeat=2)
                else:
                    # Fast 3-torus enumeration: choose first two triangles, derive
                    # all third-coordinate values compatible with their 3x3 section.
                    tri_sets=[]
                    for t1 in triangles:
                        for t2 in triangles:
                            allowed=[]
                            for z in range(q):
                                good=True
                                for x in t1:
                                    for y in t2:
                                        d=list(base)
                                        for i,v in zip(act,(x,y,z)):d[i]=v
                                        if enc(d) not in V:good=False;break
                                    if not good:break
                                if good:allowed.append(z)
                            for t3 in combinations(allowed,3):tri_sets.append((t1,t2,t3))
                for tris in tri_sets:
                    good=True
                    for vv in product(*tris):
                        d=list(base)
                        for i,v in zip(act,vv):d[i]=v
                        if enc(d) not in V:good=False;break
                    if not good:continue
                    chain=0
                    for es in product(*(tri_edges[t] for t in tris)):
                        c=list(base)
                        for i,e in zip(act,es):c[i]=e
                        chain^=1<<idx[tuple(c)]
                    x=chain
                    while x:
                        p=x.bit_length()-1
                        if p in basis:x^=basis[p]
                        else:break
                    if x and add(chain,basis):
                        found+=1;byact[act]=byact.get(act,0)+1
        assert found==betti[r],(q,r,found,betti[r],byact)
        results[r]=(found,byact)
    return len(V),betti,results

EXPECTED={4:(120,[1,15,8]),5:(385,[1,30,66]),6:(1118,[1,50,276,72])}
for q,maxr in [(4,2),(5,2),(6,3)]:
    v,b,res=analyse(q,maxr); ev,eb=EXPECTED[q]; assert v==ev and b[:maxr+1]==eb
    print('q=',q,'vertices=',v,'betti=',tuple(b[:maxr+1]))
    for r,(n,by) in res.items():print('  H%d product-torus basis'%r,n,'by coordinates',by)

print('For q=4..6 every observed executable homology class through H3 is represented by a product of local state triangles.')
print('PASS executable product-torus generators')
