#!/usr/bin/env python3
"""Interpret low-dimensional homology of the q=4 developable fibre.

States per cube Face: 0 absent, 1 root, 2 child A, 3 child B.
The calculation shows that H1 is generated by support/absence triangles on every
non-source Face, while H2 has eight 3x3 square-torus representatives coupling
one middle Face with the terminal x1 Face.
"""
from itertools import combinations, product
import sys
V={int(x) for x in open(sys.argv[1]) if x.strip()}; q=4; pw=[1,4,16,64,256,1024]
def dec(c):
    d=[]
    for _ in range(6): d.append(c%4); c//=4
    return tuple(d)
def enc(d): return sum(x*pw[i] for i,x in enumerate(d))
verts=sorted(V)
# Edges.
edges=[]; eid={}
for c in verts:
    d=list(dec(c))
    for i in range(6):
        old=d[i]
        for nv in range(old+1,4):
            d[i]=nv; z=enc(d); d[i]=old
            if z in V: eid[(c,z)]=len(edges); edges.append((c,z,i))
def E(a,b):
    if a>b: a,b=b,a
    return eid[(a,b)]
# Squares and cubes as canonical coordinate specs.
pairs=list(combinations(range(4),2))
def cells(k):
    out=[]
    for act in combinations(range(6),k):
        fixed=[i for i in range(6) if i not in act]
        for prs in product(pairs,repeat=k):
            for vals in product(range(4),repeat=6-k):
                spec=[None]*6
                for i,v in zip(fixed,vals): spec[i]=v
                for i,p in zip(act,prs): spec[i]=p
                good=True
                for bits in product((0,1),repeat=k):
                    d=list(spec)
                    for i,p,b in zip(act,prs,bits): d[i]=p[b]
                    if enc(d) not in V: good=False; break
                if good: out.append(tuple(spec))
    return out
squares=cells(2); cubes=cells(3); sidx={s:i for i,s in enumerate(squares)}
def boundary_specs(c):
    out=[]
    for i,x in enumerate(c):
        if isinstance(x,tuple):
            for v in x:
                y=list(c); y[i]=v; out.append(tuple(y))
    return out
# Square boundaries in edge space.
def square_edges(s):
    act=[i for i,x in enumerate(s) if isinstance(x,tuple)]; assert len(act)==2
    i,j=act; pi,pj=s[i],s[j]; cs=[]
    for ai in pi:
        for aj in pj:
            d=list(s); d[i]=ai; d[j]=aj; cs.append(enc(d))
    a,b,c,d=cs
    return (1<<E(a,b))^(1<<E(a,c))^(1<<E(b,d))^(1<<E(c,d))
def add(vec,basis):
    x=vec
    while x:
        p=x.bit_length()-1
        if p in basis: x^=basis[p]
        else: basis[p]=x; return True
    return False
image_d2={}
for s in squares: add(square_edges(s),image_d2)
rank_d2=len(image_d2); assert rank_d2==252
# Coordinate triangles.  They generate exactly H1 modulo square boundaries.
triangles=[]
for i in range(6):
    other=[j for j in range(6) if j!=i]
    for vals in product(range(4),repeat=5):
        d=[0]*6
        for j,v in zip(other,vals): d[j]=v
        avail=[]
        for v in range(4): d[i]=v; c=enc(d); avail.append(c if c in V else None)
        ids=[v for v,c in enumerate(avail) if c is not None]
        for tri in combinations(ids,3):
            cs=[avail[v] for v in tri]
            bits=(1<<E(cs[0],cs[1]))^(1<<E(cs[1],cs[2]))^(1<<E(cs[0],cs[2]))
            triangles.append((bits,i,tri,tuple(dec(cs[0])[j] for j in other)))
basis=dict(image_d2); h1=[]
for bits,i,tri,ctx in triangles:
    x=bits
    while x:
        p=x.bit_length()-1
        if p in basis: x^=basis[p]
        else: break
    if x and add(bits,basis): h1.append((i,tri,ctx))
assert len(h1)==15
bycoord={}
for i,tri,ctx in h1: bycoord.setdefault(i+1,[]).append(tri)
assert set(bycoord)=={2,3,4,5,6}
assert all(len(v)==3 for v in bycoord.values())
# Kernel d2 with square-combination tracking.
piv={}; ker=[]
for j,s in enumerate(squares):
    x=square_edges(s); comb=1<<j
    while x:
        p=x.bit_length()-1
        if p in piv:
            pv,pc=piv[p]; x^=pv; comb^=pc
        else: piv[p]=(x,comb); break
    if x==0: ker.append(comb)
assert len(ker)==106
# Image d3 in square space.
image_d3={}
for c in cubes:
    sb=0
    for s in boundary_specs(c): sb ^= 1<<sidx[s]
    add(sb,image_d3)
assert len(image_d3)==98
basis=dict(image_d3); h2=[]
for cyc in ker:
    x=cyc
    while x:
        p=x.bit_length()-1
        if p in basis: x^=basis[p]
        else: break
    if x and add(cyc,basis): h2.append(cyc)
assert len(h2)==8
pair_classes={}
for cyc in h2:
    ids=[j for j in range(len(squares)) if (cyc>>j)&1]
    assert len(ids)==9
    acts={tuple(i+1 for i,x in enumerate(squares[j]) if isinstance(x,tuple)) for j in ids}
    assert len(acts)==1
    pair=next(iter(acts)); pair_classes[pair]=pair_classes.get(pair,0)+1
assert pair_classes=={(2,6):2,(3,6):2,(4,6):2,(5,6):2}
print('H1 generators: 15 coordinate triangles = 3 for each non-source Face 2..6')
for i in sorted(bycoord): print('  face',i,'triangle bases',bycoord[i])
print('H2 generators: 8 nine-square product tori; active coordinate pairs',pair_classes)
print('PASS interpreted q=4 developable homology')
